import type { ProductInput } from "../types/product.js";

const categoryPriority = {
  Coffee: 10,
  "Hladne kave": 11,
  "Non carbonated drinks": 20,
  "Carbonated drinks": 21,
  Beer: 30,
  Spirits: 40,
  Liqueurs: 41,
  Wine: 50,
  "Ice cream": 60,
  Cocktails: 90
} as const;

function product(
  name: string,
  category: keyof typeof categoryPriority,
  printPriority: number,
  price: number,
  optionalFlag?: string
): ProductInput {
  return {
    name,
    category,
    categoryPriority: categoryPriority[category],
    printPriority,
    price,
    ...(optionalFlag ? { optionalFlag } : {})
  };
}

export const defaultProducts: ProductInput[] = [
  product("Espresso kava", "Coffee", 10, 1.5, "Produzeni"),
  product("Mala ladno", "Coffee", 20, 1.5),
  product("Mala toplo", "Coffee", 30, 1.5),
  product("Velika ladno", "Coffee", 40, 2),
  product("Velika toplo", "Coffee", 50, 2),
  product("Americano s mlijekom", "Coffee", 60, 3),
  product("Americano BEZ mlijeka", "Coffee", 65, 3),
  product("Espresso kava s slagom", "Coffee", 70, 2),
  product("Nescafe", "Coffee", 80, 3),
  product("Bijela kava", "Coffee", 90, 2.5),
  product("Velika espresso kava s slagom", "Coffee", 100, 2.5),
  product("Caffe Latte", "Coffee", 110, 3),
  product("Cappuccino", "Coffee", 999, 3),
  product("Hladni Nescafe vanilija", "Hladne kave", 10, 3),
  product("Hladni Nescafe cokolada", "Hladne kave", 20, 3),
  product("Ice coffee", "Hladne kave", 30, 3, "No sugar"),
  product("Pago jabuka", "Non carbonated drinks", 10, 3),
  product("Pago naranca", "Non carbonated drinks", 20, 3),
  product("Pago jagoda", "Non carbonated drinks", 30, 3),
  product("Pago crni ribiz", "Non carbonated drinks", 40, 3, "0.5L"),
  product("Pago marelica", "Non carbonated drinks", 50, 3),
  product("Cedevita limun", "Non carbonated drinks", 60, 2.5, "0.5L"),
  product("Cedevita naranca", "Non carbonated drinks", 70, 2.5, "0.5L"),
  product("Ice tea breskva", "Non carbonated drinks", 80, 3),
  product("Ice tea brusnica", "Non carbonated drinks", 90, 3),
  product("Prirodna negazirana voda 0,25L", "Non carbonated drinks", 100, 2),
  product("Cijedena limunada", "Non carbonated drinks", 110, 4),
  product("Tonic", "Carbonated drinks", 10, 3),
  product("Pipi", "Carbonated drinks", 20, 3),
  product("Sprite", "Carbonated drinks", 30, 3),
  product("Orangina", "Carbonated drinks", 40, 4),
  product("Coca-Cola", "Carbonated drinks", 50, 3),
  product("Bitter lemon", "Carbonated drinks", 60, 3),
  product("Romerquelle limunska trava 0,3L", "Carbonated drinks", 70, 2.5),
  product("Jamnica sensation", "Carbonated drinks", 80, 2.5),
  product("Prirodna gazirana voda 0,25L", "Carbonated drinks", 90, 2.5),
  product("Toceno pivo 0,3L", "Beer", 10, 3),
  product("Toceno pivo 0,5L", "Beer", 20, 4.5),
  product("Ozujsko 0,33L", "Beer", 30, 3),
  product("Karlovacko 0,33L", "Beer", 40, 3),
  product("Staropramen 0,33L", "Beer", 50, 3),
  product("Beck's 0,33L", "Beer", 60, 3.5),
  product("Ozujsko limun - Radler 0,33L", "Beer", 70, 3),
  product("Somersby 0,33L", "Beer", 80, 4),
  product("Pelinkovac", "Spirits", 10, 2, "Double"),
  product("Orahovac", "Spirits", 20, 2, "Double"),
  product("Travarica", "Spirits", 30, 2, "Double"),
  product("Konjak", "Spirits", 40, 2, "Double"),
  product("Rum", "Spirits", 50, 2, "Double"),
  product("Stock", "Spirits", 60, 2, "Double"),
  product("Gin", "Spirits", 70, 2, "Double"),
  product("Vodka", "Spirits", 80, 2, "Double"),
  product("Baileys liker", "Liqueurs", 10, 3.5, "Double"),
  product("Ballantine's", "Liqueurs", 20, 3, "Double"),
  product("Campari", "Liqueurs", 30, 4, "Double"),
  product("Jagermeister", "Liqueurs", 40, 3, "Double"),
  product("Malibu", "Liqueurs", 50, 3, "Double"),
  product("Bijelo vino - Grasevina 0,187L", "Wine", 10, 5),
  product("Crno vino - Plavac 0,187L", "Wine", 20, 5),
  product("Bijelo vino - Malvazija 0,1L", "Wine", 30, 2),
  product("Gemist 0,3L", "Wine", 40, 4),
  product("Sladoled na stapicu", "Ice cream", 10, 2),
  product("Kornet", "Ice cream", 20, 2.5),
  product("Magnum", "Ice cream", 30, 3.5),
  product("APEROL SPRITZ", "Cocktails", 1, 8),
  product("CAMPARI SPRITZ", "Cocktails", 2, 8),
  product("HUGO SPRITZ", "Cocktails", 3, 10),
  product("MIMOSA", "Cocktails", 4, 7),
  product("CUBA LIBRE", "Cocktails", 10, 8),
  product("BLUE HAWAII", "Cocktails", 20, 10),
  product("TEQUILA SUNRISE", "Cocktails", 30, 10),
  product("MEXICAN WAVE", "Cocktails", 40, 10),
  product("SEX ON THE BEACH", "Cocktails", 50, 10),
  product("MALIBU BAY BREEZE", "Cocktails", 60, 10),
  product("LONG ISLAND ICED TEA", "Cocktails", 70, 12),
  product("MOJITO", "Cocktails", 80, 12)
];
